/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancemanagementsystem.Student;

import attendancemanagementsystem.Database.StudentDatabase;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fahim
 */
public class StudentDashboard extends javax.swing.JFrame {

    private Connection conn;
    private StudentDatabase studentDatabase;
    final JPanel panel = new JPanel();

    public StudentDashboard() {
        initComponents();
        initialSetup();
    }

    public StudentDashboard(Connection conn, StudentDatabase studentDatabase) {
        initComponents();
        this.conn = conn;
        this.studentDatabase = studentDatabase;
        initialSetup();
        getStudentProfile();
    }
//----------------------------Custom methods starts-------------------------//

    private void initialSetup() {
        submitUpdateButton.setVisible(false);
        confirmPassLabel.setVisible(false);
        studentAddress.setLineWrap(true);
    }

    private void getStudentProfile() {
        studentIdTextField.setText(studentDatabase.getStudentId());
        studentNameTextField.setText(studentDatabase.getStudentName());
        studentEmailTextField.setText(studentDatabase.getStudentEmail());
        studentPhoneTextField.setText(studentDatabase.getStudentPhone());
        studentAddress.setText(studentDatabase.getStudentAddress());
        studentBloodGroup.setText(studentDatabase.getStudentBloodGroup());
        setTextFieldsEditableFalse();
        studentNewPassField.setText("");
        studentConfirmPassField.setText("");
    }

    private void setTextFieldsEditableTrue() {
        studentNameTextField.setEditable(true);
        studentEmailTextField.setEditable(true);
        studentPhoneTextField.setEditable(true);
        studentAddress.setEditable(true);
        studentBloodGroup.setEditable(true);
        studentNewPassField.setEditable(true);
        studentConfirmPassField.setEditable(true);
    }

    private void setTextFieldsEditableFalse() {
        studentNameTextField.setEditable(false);
        studentEmailTextField.setEditable(false);
        studentPhoneTextField.setEditable(false);
        studentAddress.setEditable(false);
        studentBloodGroup.setEditable(false);
        studentNewPassField.setEditable(false);
        studentConfirmPassField.setEditable(false);
    }

    //----------------------------Custom methods ends-------------------------//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JPanel();
        adminProfileLabel = new javax.swing.JLabel();
        studentIdLabel = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        studentPhoneTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        studentEmailTextField = new javax.swing.JTextField();
        updateProfileButton = new javax.swing.JButton();
        submitUpdateButton = new javax.swing.JButton();
        phoneLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        studentNewPassField = new javax.swing.JPasswordField();
        studentConfirmPassField = new javax.swing.JPasswordField();
        phoneLabel2 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        studentBloodGroup = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentAddress = new javax.swing.JTextArea();
        confirmPassLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        studentAttendanceTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        giveAttendanceButton = new javax.swing.JButton();
        giveAttendanceButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminProfileLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        adminProfileLabel.setText("Student Profile");

        studentIdLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        studentIdLabel.setText("Login Id");

        studentIdTextField.setEditable(false);
        studentIdTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nameLabel.setText("Name");

        studentNameTextField.setEditable(false);
        studentNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        phoneLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel.setText("Phone");

        studentPhoneTextField.setEditable(false);
        studentPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        emailLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel.setText("Email");

        studentEmailTextField.setEditable(false);
        studentEmailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        updateProfileButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updateProfileButton.setText("Update Profile");
        updateProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateProfileButtonMouseClicked(evt);
            }
        });

        submitUpdateButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitUpdateButton.setText("Submit Update");
        submitUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitUpdateButtonMouseClicked(evt);
            }
        });
        submitUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateButtonActionPerformed(evt);
            }
        });

        phoneLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel1.setText("Confirm Password");

        emailLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel1.setText("New Password");

        studentNewPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        studentConfirmPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        phoneLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel2.setText("Blood Group");

        emailLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel2.setText("Address");

        studentBloodGroup.setEditable(false);
        studentBloodGroup.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        studentAddress.setEditable(false);
        studentAddress.setColumns(20);
        studentAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddress.setRows(5);
        jScrollPane2.setViewportView(studentAddress);

        confirmPassLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        confirmPassLabel.setForeground(new java.awt.Color(255, 0, 51));
        confirmPassLabel.setText("* You have to confirm your password");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneLabel1)
                                    .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProfileLayout.createSequentialGroup()
                                        .addComponent(studentConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(confirmPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(studentNewPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(submitUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addComponent(phoneLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(studentBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(studentIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studentIdTextField)
                                    .addComponent(studentNameTextField)
                                    .addComponent(studentEmailTextField)
                                    .addComponent(studentPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(adminProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(40, 40, 40)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNewPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitUpdateButton)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Profile", Profile);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Attendance Date");

        giveAttendanceButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        giveAttendanceButton.setText("Update Attendance");

        giveAttendanceButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        giveAttendanceButton1.setText("Give Attendance");

        javax.swing.GroupLayout studentAttendanceTabLayout = new javax.swing.GroupLayout(studentAttendanceTab);
        studentAttendanceTab.setLayout(studentAttendanceTabLayout);
        studentAttendanceTabLayout.setHorizontalGroup(
            studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                        .addGroup(studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                        .addGroup(studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(giveAttendanceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giveAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        studentAttendanceTabLayout.setVerticalGroup(
            studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                .addGroup(studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(giveAttendanceButton1)
                        .addGap(38, 38, 38)
                        .addComponent(giveAttendanceButton)))
                .addGap(0, 154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Attendance", studentAttendanceTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitUpdateButtonActionPerformed

    private void updateProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileButtonMouseClicked
        setTextFieldsEditableTrue();
        submitUpdateButton.setVisible(true);
        updateProfileButton.setVisible(false);
    }//GEN-LAST:event_updateProfileButtonMouseClicked

    private void submitUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitUpdateButtonMouseClicked
        if (studentDatabase.getStudentPass().equals(studentConfirmPassField.getText())) {
            String studentPass;
            confirmPassLabel.setVisible(false);
            if (!studentNewPassField.getText().equals("")) {
                studentPass = studentNewPassField.getText();
            } else {
                studentPass = studentDatabase.getStudentPass();
            }
            boolean updateDone = studentDatabase.updateProfile(studentPass, studentNameTextField.getText(), studentEmailTextField.getText(), studentPhoneTextField.getText(), studentAddress.getText(), studentBloodGroup.getText());
            if (updateDone) {
                JOptionPane.showMessageDialog(panel, "Your profile has been updated successfully", "Successful Update", JOptionPane.INFORMATION_MESSAGE);
                updateProfileButton.setVisible(true);
                submitUpdateButton.setVisible(false);
                getStudentProfile();
            }
        } else {
            confirmPassLabel.setVisible(true);
        }
    }//GEN-LAST:event_submitUpdateButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new StudentLoginForm(conn).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel adminProfileLabel;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JButton giveAttendanceButton;
    private javax.swing.JButton giveAttendanceButton1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JLabel phoneLabel2;
    private javax.swing.JTextArea studentAddress;
    private javax.swing.JPanel studentAttendanceTab;
    private javax.swing.JTextField studentBloodGroup;
    private javax.swing.JPasswordField studentConfirmPassField;
    private javax.swing.JTextField studentEmailTextField;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JPasswordField studentNewPassField;
    private javax.swing.JTextField studentPhoneTextField;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton submitUpdateButton;
    private javax.swing.JButton updateProfileButton;
    // End of variables declaration//GEN-END:variables
}
