/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancemanagementsystem.Student;

import attendancemanagementsystem.Database.StudentDatabase;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fahim
 */
public class StudentDashboard extends javax.swing.JFrame {

    private Connection conn;
    private StudentDatabase studentDatabase;
    final JPanel panel = new JPanel();

    public StudentDashboard() {
        initComponents();
        initialSetup();
    }

    public StudentDashboard(Connection conn, StudentDatabase studentDatabase) {
        initComponents();
        this.conn = conn;
        this.studentDatabase = studentDatabase;
        initialSetup();
        getStudentProfile();
    }
//----------------------------Custom methods starts-------------------------//

    private void getAttendance(int month) {
        boolean[] attendance = studentDatabase.getAttendance(month);
        DefaultTableModel dtm = (DefaultTableModel) attendanceTable.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[2];
        for (int i = 1; i <= 30; i++) {
            row[0] = "Day " + (i);
            if (attendance[i] == true) {
                row[1] = "Present";
            } else {
                row[1] = "Absent";
            }
            dtm.addRow(row);
        }
    }

    private void initialSetup() {
        submitUpdateButton.setVisible(false);
        confirmPassLabel.setVisible(false);
        studentAddress.setLineWrap(true);
    }

    private void getStudentProfile() {
        studentIdTextField.setText(studentDatabase.getStudentId());
        studentNameTextField.setText(studentDatabase.getStudentName());
        studentEmailTextField.setText(studentDatabase.getStudentEmail());
        studentPhoneTextField.setText(studentDatabase.getStudentPhone());
        studentAddress.setText(studentDatabase.getStudentAddress());
        studentBloodGroup.setText(studentDatabase.getStudentBloodGroup());
        setTextFieldsEditableFalse();
        studentNewPassField.setText("");
        studentConfirmPassField.setText("");
    }

    private void setTextFieldsEditableTrue() {
        studentNameTextField.setEditable(true);
        studentEmailTextField.setEditable(true);
        studentPhoneTextField.setEditable(true);
        studentAddress.setEditable(true);
        studentBloodGroup.setEditable(true);
        studentNewPassField.setEditable(true);
        studentConfirmPassField.setEditable(true);
    }

    private void setTextFieldsEditableFalse() {
        studentNameTextField.setEditable(false);
        studentEmailTextField.setEditable(false);
        studentPhoneTextField.setEditable(false);
        studentAddress.setEditable(false);
        studentBloodGroup.setEditable(false);
        studentNewPassField.setEditable(false);
        studentConfirmPassField.setEditable(false);
    }

    //----------------------------Custom methods ends-------------------------//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JPanel();
        adminProfileLabel = new javax.swing.JLabel();
        studentIdLabel = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        studentPhoneTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        studentEmailTextField = new javax.swing.JTextField();
        updateProfileButton = new javax.swing.JButton();
        submitUpdateButton = new javax.swing.JButton();
        phoneLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        studentNewPassField = new javax.swing.JPasswordField();
        studentConfirmPassField = new javax.swing.JPasswordField();
        phoneLabel2 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        studentBloodGroup = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentAddress = new javax.swing.JTextArea();
        confirmPassLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        studentAttendanceTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        showAttendanceButton = new javax.swing.JButton();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminProfileLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        adminProfileLabel.setText("Student Profile");
        Profile.add(adminProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 0, 261, 48));

        studentIdLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        studentIdLabel.setText("Login Id");
        Profile.add(studentIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 99, 120, 29));

        studentIdTextField.setEditable(false);
        studentIdTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Profile.add(studentIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 91, 280, 33));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nameLabel.setText("Name");
        Profile.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 146, 120, 29));

        studentNameTextField.setEditable(false);
        studentNameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Profile.add(studentNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 142, 280, 33));

        phoneLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel.setText("Phone");
        Profile.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 120, 29));

        studentPhoneTextField.setEditable(false);
        studentPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Profile.add(studentPhoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 280, 33));

        emailLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel.setText("Email");
        Profile.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 120, 29));

        studentEmailTextField.setEditable(false);
        studentEmailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEmailTextFieldActionPerformed(evt);
            }
        });
        Profile.add(studentEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 280, 33));

        updateProfileButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updateProfileButton.setText("Update Profile");
        updateProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateProfileButtonMouseClicked(evt);
            }
        });
        Profile.add(updateProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 615, 173, -1));

        submitUpdateButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitUpdateButton.setText("Submit Update");
        submitUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitUpdateButtonMouseClicked(evt);
            }
        });
        submitUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateButtonActionPerformed(evt);
            }
        });
        Profile.add(submitUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 667, 173, -1));

        phoneLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel1.setText("Confirm Password");
        Profile.add(phoneLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 560, -1, 29));

        emailLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel1.setText("New Password");
        Profile.add(emailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 508, 212, 29));

        studentNewPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Profile.add(studentNewPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 504, 262, 40));

        studentConfirmPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Profile.add(studentConfirmPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 556, 263, 40));

        phoneLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel2.setText("Blood Group");
        Profile.add(phoneLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 157, 29));

        emailLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel2.setText("Address");
        Profile.add(emailLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 120, 29));

        studentBloodGroup.setEditable(false);
        studentBloodGroup.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Profile.add(studentBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 81, 33));

        studentAddress.setEditable(false);
        studentAddress.setColumns(20);
        studentAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddress.setRows(5);
        jScrollPane2.setViewportView(studentAddress);

        Profile.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 280, 90));

        confirmPassLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        confirmPassLabel.setForeground(new java.awt.Color(255, 0, 51));
        confirmPassLabel.setText("* You have to confirm your password");
        Profile.add(confirmPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 557, 312, 40));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        Profile.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1019, 11, 132, -1));

        jTabbedPane1.addTab("Profile", Profile);

        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "Attendance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attendanceTable);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Attendance Month");

        showAttendanceButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showAttendanceButton.setText("Show Attendance");
        showAttendanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAttendanceButtonMouseClicked(evt);
            }
        });

        jMonthChooser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMonthChooserFocusGained(evt);
            }
        });
        jMonthChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooserPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout studentAttendanceTabLayout = new javax.swing.GroupLayout(studentAttendanceTab);
        studentAttendanceTab.setLayout(studentAttendanceTabLayout);
        studentAttendanceTabLayout.setHorizontalGroup(
            studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        studentAttendanceTabLayout.setVerticalGroup(
            studentAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAttendanceTabLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(showAttendanceButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("My Attendance", studentAttendanceTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitUpdateButtonActionPerformed

    private void updateProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileButtonMouseClicked
        setTextFieldsEditableTrue();
        submitUpdateButton.setVisible(true);
        updateProfileButton.setVisible(false);
    }//GEN-LAST:event_updateProfileButtonMouseClicked

    private void submitUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitUpdateButtonMouseClicked
        if (studentDatabase.getStudentPass().equals(studentConfirmPassField.getText())) {
            String studentPass;
            confirmPassLabel.setVisible(false);
            if (!studentNewPassField.getText().equals("")) {
                studentPass = studentNewPassField.getText();
            } else {
                studentPass = studentDatabase.getStudentPass();
            }
            boolean updateDone = studentDatabase.updateProfile(studentPass, studentNameTextField.getText(), studentEmailTextField.getText(), studentPhoneTextField.getText(), studentAddress.getText(), studentBloodGroup.getText());
            if (updateDone) {
                JOptionPane.showMessageDialog(panel, "Your profile has been updated successfully", "Successful Update", JOptionPane.INFORMATION_MESSAGE);
                updateProfileButton.setVisible(true);
                submitUpdateButton.setVisible(false);
                getStudentProfile();
            }
        } else {
            confirmPassLabel.setVisible(true);
        }
    }//GEN-LAST:event_submitUpdateButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new StudentLoginForm(conn).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void showAttendanceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAttendanceButtonMouseClicked
        getAttendance(jMonthChooser.getMonth() + 1);
    }//GEN-LAST:event_showAttendanceButtonMouseClicked

    private void jMonthChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMonthChooserPropertyChange

    }//GEN-LAST:event_jMonthChooserPropertyChange

    private void jMonthChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMonthChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jMonthChooserFocusGained

    private void studentEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel adminProfileLabel;
    private javax.swing.JTable attendanceTable;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JLabel phoneLabel2;
    private javax.swing.JButton showAttendanceButton;
    private javax.swing.JTextArea studentAddress;
    private javax.swing.JPanel studentAttendanceTab;
    private javax.swing.JTextField studentBloodGroup;
    private javax.swing.JPasswordField studentConfirmPassField;
    private javax.swing.JTextField studentEmailTextField;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JPasswordField studentNewPassField;
    private javax.swing.JTextField studentPhoneTextField;
    private javax.swing.JButton submitUpdateButton;
    private javax.swing.JButton updateProfileButton;
    // End of variables declaration//GEN-END:variables
}
