/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancemanagementsystem.Admin;

import attendancemanagementsystem.Database.AdminDatabase;
import attendancemanagementsystem.Database.StudentDatabase;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class AdminDashboard extends javax.swing.JFrame {

    private Connection conn;
    private AdminDatabase adminDatabase;
    final JPanel panel = new JPanel();

    public AdminDashboard() {
        initComponents();
        initialSetup();
    }

    public AdminDashboard(Connection conn, AdminDatabase adminDatabase) {
        initComponents();
        this.conn = conn;
        initialSetup();
        this.adminDatabase = adminDatabase;
        getAdminProfile();
        getStudentData();
    }

    //----------------------------Custom methods starts-------------------------//
    private void initialSetup() {
        submitUpdateButton.setVisible(false);
        confirmPassLabel.setVisible(false);
    }

    private void getStudentData() {
        DefaultTableModel dtm = (DefaultTableModel) studentTable.getModel();
        dtm.setRowCount(0);
        List<StudentDatabase> list = (List<StudentDatabase>) adminDatabase.getStudentData();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getStudentId();
            row[1] = list.get(i).getStudentName();
            row[2] = list.get(i).getStudentEmail();
            row[3] = list.get(i).getStudentPhone();
            dtm.addRow(row);
        }
    }

    private void addStudentData(String studentId) {
        DefaultTableModel dtm = (DefaultTableModel) studentTable.getModel();
        Object[] row = new Object[4];

        row[0] = studentId;
        row[1] = "";
        row[2] = "";
        row[3] = "";
        dtm.addRow(row);

    }

    private void getAdminProfile() {
        adminNameTextField.setText(adminDatabase.getAdminName());
        adminUsernameTextField.setText(adminDatabase.getAdminUsername());
        adminEmailTextField.setText(adminDatabase.getAdminEmail());
        adminPhoneTextField.setText(adminDatabase.getAdminPhone());
        setTextFieldsEditableFalse();
        adminNewPassField.setText("");
        adminConfirmPassField.setText("");
    }

    private void setTextFieldsEditableTrue() {
        adminNameTextField.setEditable(true);
        adminEmailTextField.setEditable(true);
        adminPhoneTextField.setEditable(true);
        adminNewPassField.setEditable(true);
        adminConfirmPassField.setEditable(true);
    }

    private void setTextFieldsEditableFalse() {
        adminUsernameTextField.setEditable(false);
        adminEmailTextField.setEditable(false);
        adminPhoneTextField.setEditable(false);
        adminNewPassField.setEditable(false);
        adminConfirmPassField.setEditable(false);
    }

    //----------------------------Custom methods ends-------------------------//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JPanel();
        adminProfileLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        adminNameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        adminUsernameTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        adminPhoneTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        adminEmailTextField = new javax.swing.JTextField();
        updateProfileButton = new javax.swing.JButton();
        submitUpdateButton = new javax.swing.JButton();
        phoneLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        adminNewPassField = new javax.swing.JPasswordField();
        adminConfirmPassField = new javax.swing.JPasswordField();
        confirmPassLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        studentsAttendanceTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        updateAttendanceButton = new javax.swing.JButton();
        giveAttendanceButton = new javax.swing.JButton();
        jDayChooser = new com.toedter.calendar.JDayChooser();
        jLabel7 = new javax.swing.JLabel();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        ManageStudentAccountTab = new javax.swing.JPanel();
        createUserButton = new javax.swing.JButton();
        studentLoginIdTextFiled = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createStudentAccountLabel = new javax.swing.JLabel();
        loginIdToDeleteTextFiled = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deleteUserButton = new javax.swing.JButton();
        studentPassField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        adminProfileLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        adminProfileLabel.setText("Admin Profile");

        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        usernameLabel.setText("Username");

        adminNameTextField.setEditable(false);
        adminNameTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nameLabel.setText("Name");

        adminUsernameTextField.setEditable(false);
        adminUsernameTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        phoneLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel.setText("Phone");

        adminPhoneTextField.setEditable(false);
        adminPhoneTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        emailLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel.setText("Email");

        adminEmailTextField.setEditable(false);
        adminEmailTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        updateProfileButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updateProfileButton.setText("Update Profile");
        updateProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateProfileButtonMouseClicked(evt);
            }
        });

        submitUpdateButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitUpdateButton.setText("Submit Update");
        submitUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitUpdateButtonMouseClicked(evt);
            }
        });
        submitUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateButtonActionPerformed(evt);
            }
        });

        phoneLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneLabel1.setText("Confirm Password");

        emailLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailLabel1.setText("New Password");

        adminNewPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        adminConfirmPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        confirmPassLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        confirmPassLabel.setForeground(new java.awt.Color(255, 0, 51));
        confirmPassLabel.setText("* You have to confirm your password");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(adminUsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                        .addComponent(adminEmailTextField))
                                    .addComponent(adminPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminNameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phoneLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminNewPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(adminProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminProfileLabel)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminNewPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminConfirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(updateProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitUpdateButton)
                .addGap(169, 169, 169))
        );

        jTabbedPane1.addTab("Profile", Profile);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Attendance Month");

        updateAttendanceButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updateAttendanceButton.setText("Update Attendance");
        updateAttendanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateAttendanceButtonMouseClicked(evt);
            }
        });

        giveAttendanceButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        giveAttendanceButton.setText("Give Attendance");
        giveAttendanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giveAttendanceButtonMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Attendance Day");

        javax.swing.GroupLayout studentsAttendanceTabLayout = new javax.swing.GroupLayout(studentsAttendanceTab);
        studentsAttendanceTab.setLayout(studentsAttendanceTabLayout);
        studentsAttendanceTabLayout.setHorizontalGroup(
            studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentsAttendanceTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentsAttendanceTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentsAttendanceTabLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(studentsAttendanceTabLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giveAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentsAttendanceTabLayout.createSequentialGroup()
                    .addContainerGap(954, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)))
        );
        studentsAttendanceTabLayout.setVerticalGroup(
            studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentsAttendanceTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(studentsAttendanceTabLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jDayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(giveAttendanceButton)
                .addGap(18, 18, 18)
                .addComponent(updateAttendanceButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(studentsAttendanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(studentsAttendanceTabLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Students", studentsAttendanceTab);

        createUserButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        createUserButton.setText("Create User");
        createUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUserButtonMouseClicked(evt);
            }
        });

        studentLoginIdTextFiled.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Login ID");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Password");

        createStudentAccountLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        createStudentAccountLabel.setText("Create Student Account");

        loginIdToDeleteTextFiled.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Login ID");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Delete Student Account");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Your Password");

        deleteUserButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteUserButton.setText("Delete User");
        deleteUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserButtonMouseClicked(evt);
            }
        });

        studentPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        studentPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentPassFieldKeyPressed(evt);
            }
        });

        confirmPassField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout ManageStudentAccountTabLayout = new javax.swing.GroupLayout(ManageStudentAccountTab);
        ManageStudentAccountTab.setLayout(ManageStudentAccountTabLayout);
        ManageStudentAccountTabLayout.setHorizontalGroup(
            ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(createStudentAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                                .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studentLoginIdTextFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(studentPassField)))))
                    .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageStudentAccountTabLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageStudentAccountTabLayout.createSequentialGroup()
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginIdToDeleteTextFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(confirmPassField))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageStudentAccountTabLayout.createSequentialGroup()
                        .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))))
        );
        ManageStudentAccountTabLayout.setVerticalGroup(
            ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginIdToDeleteTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                        .addComponent(createStudentAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentLoginIdTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ManageStudentAccountTabLayout.createSequentialGroup()
                                .addComponent(studentPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(35, 35, 35)
                        .addGroup(ManageStudentAccountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createUserButton)
                            .addComponent(deleteUserButton))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Student Account", ManageStudentAccountTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitUpdateButtonActionPerformed

    private void createUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserButtonMouseClicked
        String studentId = studentLoginIdTextFiled.getText();
        adminDatabase.createStudentAccount(studentId, studentPassField.getText());
        addStudentData(studentId);
        studentLoginIdTextFiled.setText("");
        studentPassField.setText("");
    }//GEN-LAST:event_createUserButtonMouseClicked

    private void studentPassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentPassFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentPassFieldKeyPressed

    private void updateProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProfileButtonMouseClicked
        setTextFieldsEditableTrue();
        submitUpdateButton.setVisible(true);
        updateProfileButton.setVisible(false);
    }//GEN-LAST:event_updateProfileButtonMouseClicked

    private void submitUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitUpdateButtonMouseClicked
        if (adminDatabase.getAdminPass().equals(adminConfirmPassField.getText())) {
            String adminPass;
            confirmPassLabel.setVisible(false);
            if (!adminNewPassField.getText().equals("")) {
                adminPass = adminNewPassField.getText();
            } else {
                adminPass = adminDatabase.getAdminPass();
            }
            boolean updateDone = adminDatabase.updateProfile(adminPass, adminNameTextField.getText(), adminEmailTextField.getText(), adminPhoneTextField.getText());
            if (updateDone) {
                JOptionPane.showMessageDialog(panel, "Your profile has been updated successfully", "Successful Update", JOptionPane.INFORMATION_MESSAGE);
                updateProfileButton.setVisible(true);
                submitUpdateButton.setVisible(false);
                getAdminProfile();
            }
        } else {
            confirmPassLabel.setVisible(true);
        }
    }//GEN-LAST:event_submitUpdateButtonMouseClicked

    private void deleteUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserButtonMouseClicked
        if (adminDatabase.getAdminPass().equals(confirmPassField.getText())) {
            if (adminDatabase.deleteStudentAccount(loginIdToDeleteTextFiled.getText())) {
                JOptionPane.showMessageDialog(panel, "Account has been deleted successfully", "Successful Delete", JOptionPane.INFORMATION_MESSAGE);
                loginIdToDeleteTextFiled.setText("");
                confirmPassField.setText("");
                getStudentData();
            } else {
                JOptionPane.showMessageDialog(panel, "Something went wrong", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(panel, "You have to confirm your password", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_deleteUserButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new AdminLoginForm(conn).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void giveAttendanceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giveAttendanceButtonMouseClicked
        int day = jDayChooser.getDay();
        int month = jMonthChooser.getMonth() + 1;
        String dayColumn;
        DefaultTableModel dtm = (DefaultTableModel) studentTable.getModel();

        String id, sql;
        if (studentTable.getRowCount() == 0) {
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "There is no data to delete.", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            int[] rows = studentTable.getSelectedRows();
            if (rows.length == 0) {
                JOptionPane.showMessageDialog(panel, "No row selected.", "No selection",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (int i = 0; i < rows.length; i++) {
                    id = dtm.getValueAt(rows[i], 0).toString();
                    dayColumn = "D" + day;
                    adminDatabase.giveAttendance(id, dayColumn, month);
                }
                JOptionPane.showMessageDialog(panel, "Attendance has been updated.", "No selection",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_giveAttendanceButtonMouseClicked

    private void updateAttendanceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateAttendanceButtonMouseClicked
        int day = jDayChooser.getDay();
        int month = jMonthChooser.getMonth() + 1;
        String dayColumn;
        DefaultTableModel dtm = (DefaultTableModel) studentTable.getModel();

        String id, sql;
        if (studentTable.getRowCount() == 0) {
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "There is no data to delete.", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            int[] rows = studentTable.getSelectedRows();
            if (rows.length == 0) {
                JOptionPane.showMessageDialog(panel, "No row selected.", "No selection",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (int i = 0; i < rows.length; i++) {
                    id = dtm.getValueAt(rows[i], 0).toString();
                    dayColumn = "D" + day;
                    adminDatabase.giveAttendance(id, dayColumn, month);
                }
                JOptionPane.showMessageDialog(panel, "Attendance has been updated.", "No selection",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateAttendanceButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ManageStudentAccountTab;
    private javax.swing.JPanel Profile;
    private javax.swing.JPasswordField adminConfirmPassField;
    private javax.swing.JTextField adminEmailTextField;
    private javax.swing.JTextField adminNameTextField;
    private javax.swing.JPasswordField adminNewPassField;
    private javax.swing.JTextField adminPhoneTextField;
    private javax.swing.JLabel adminProfileLabel;
    private javax.swing.JTextField adminUsernameTextField;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JLabel createStudentAccountLabel;
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JButton giveAttendanceButton;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDayChooser jDayChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField loginIdToDeleteTextFiled;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JTextField studentLoginIdTextFiled;
    private javax.swing.JPasswordField studentPassField;
    private javax.swing.JTable studentTable;
    private javax.swing.JPanel studentsAttendanceTab;
    private javax.swing.JButton submitUpdateButton;
    private javax.swing.JButton updateAttendanceButton;
    private javax.swing.JButton updateProfileButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
